name: Common Sonar Scan (Gradle)

on:
  workflow_call:
    inputs:
      coverage-artifact:
        required: false
        type: string
        default: "coverage"

    secrets:
      SONAR_TOKEN:
        required: true
      SONAR_HOST_URL:
        required: true

jobs:
  sonar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Download coverage artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.coverage-artifact }}
          path: .

      - name: Run SonarQube Scan via Gradle
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        run: |
          chmod +x gradlew
          ./gradlew sonar --no-configuration-cache --stacktrace
