name: Common FTP Upload

on:
  workflow_call:
    inputs:
      target-path:
        required: true
        type: string
        description: "target path in ftp server"

      artifact-name:
        required: false
        type: string
        default: "build-artifacts"

    secrets:
      FTP_HOST:
        required: true
      FTP_USER:
        required: true
      FTP_PASSWORD:
        required: true

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ./upload

      - name: Perform uploads
        run: |
          DST="${{ inputs.target-path }}"

          find ./upload -type f | while read FILE; do
            BASENAME=$(basename "$FILE")
            TARGET_PATH="$DST/$BASENAME"

            echo "Uploading $FILE → $TARGET_PATH"

            curl --fail --ftp-ssl --ftp-create-dirs \
              --user "${{ secrets.FTP_USER }}:${{ secrets.FTP_PASSWORD }}" \
              --upload-file "$FILE" \
              "ftp://${{ secrets.FTP_HOST }}/$TARGET_PATH"
          done
